### ISSUE TITLE
List of Jenkins jobs is cut off in "job name" auto-complete field

### ISSUE THREAD

**Issue by heyitsfranklin** [Inedo/inedox-jenkins#27] opened 2019-01-30 13:46 UTC
I have many jobs in my local Jenkins instance. When I add/edit Jenkins related operation in my Plan and a job name is required, the complete list of Jenkins jobs that appears below the Job Name field is not visible. If I type more characters, the auto-complete list is never filtered either to exclude job names that do not match the text I have entered.

The job name auto-complete field should:

1. Fully display all available jobs
2. Continue to filter the list of available jobs as the user types their job name

![screen1](https://user-images.githubusercontent.com/11930733/51984997-b0b62e80-2494-11e9-93ee-b14629233787.png)

![screen](https://user-images.githubusercontent.com/11930733/51984999-b0b62e80-2494-11e9-8746-a9395cb555ae.png)

**Comment by antony-booth** [comment] 2019-02-07 15:58
The drop down list contains the results from the following query: -
`http://<YourJenkinsServer>/api/xml?tree=jobs[name]`

It then returns a collection of `<name />` element values.

You should visit that url to confirm all your jobs are contained in the response XML, using the same credentials used in your Buildmaster, "Queue New Jenkins Build" operation.

You could also check to see if the full list is in the html `<ul>` using your browser Developer tools, determinig whether the scroll is disabled for the element.

If the problem is Jenkins pages the the jobs results in the XML and there was another query parameter in Jenkins to get all results, or next page and combine the results that way.

If the problem is scrolling, this would require a Buildmaster CSS fix, or for you to use a browser plugin like Styler to modify the css and enable scrolling.

**Comment by heyitsfranklin** [comment] 2019-02-07 16:11
@antony-booth the jobs are all returned in the response xml... furthermore, all jobs are rendered to the DOM as you can see in my screenshot above where the blue highlighted element renders past its container.

I don't understand how this is not simply fixed in BuildMaster instead of asking users to install a Chrome extension.

**Comment by antony-booth** [comment] 2019-02-07 17:00
I don't work for Inedo. I was offering you a workaround if you needed to wait for Inedo to fix an issue.
If the results are all included in the DOM, but you can not see them or select them, the fix is outside the scope of this Jenkins extension, because the user interface is generated by the Inedo SDK inside buildmaster and this extension does not control that.

I suggest you submit a request to Indeo and wait for the fix.

**Comment by heyitsfranklin** [comment] 2019-02-08 09:55
Ah yes, you're right. My apologies to you... for some reason I thought you worked for Inedo 😅I submitted a support ticket via their website.

Thanks for your help. I'll try that Chrome extension in the meantime.

**Comment by jrasch** [comment] 2019-02-14 17:25
Just wanted to let you know here we are working on this now and hope to get it in the next maintenance release: https://inedo.myjetbrains.com/youtrack/issue/SDK-31

**Comment by gdivis** [comment] 2019-02-15 16:39
This will be included in BuildMaster 6.1.1. See https://inedo.myjetbrains.com/youtrack/issue/BM-3313

**Closed by gdivis** 2019-02-15 16:39 UTC
